#!/usr/bin/perl 
#    paVolume
#    Copyright (C) 2015 Victor H. Cervantes <herulor@gmail.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
$USAGE1 = "Usage:\n\t paVolume action [deltaVol]";
$ACTION_MSG = "\nWhere action is an integer from 0 to 3. 0 to toggle mute, 1 to decrease volume by deltaVol, and 2 to raise volume by deltaVol; or 3 to show the volume status of each sink";
$DELTA_MSG = "\nWhere deltaVol is a value between -100 and 100 by which volume will be adjusted";
$EXTRA_PARAM ="More paramaters than needed, extra ones will be omited\n";
# Si no se entregan suficientes parametros nos salimos
$N_ARG = $#ARGV + 1;

if ($N_ARG > 2) {
    print STDERR $EXTRA_PARAM;
}
if ($N_ARG < 1) {
    die($USAGE1);
}

# Si se entregan más parametros que los necesarios informamos.
# Pero no son tenidos en cuenta

$ACTION = $ARGV[0];
if ($N_ARG > 1) {
    $DELTA = $ARGV[1];
} 

if (($ACTION < 0) or ($ACTION > 3)) {
    die($USAGE1.$ACTION_MSG);
}

if (($DELTA < -100) or ($DELTA > 100)) {
    die($USAGE1.$DELTA_MSG);
}

@PA_SINKS = `pactl list sinks short`;

foreach(@PA_SINKS) {
    @LINE = split('\s', $_);
    if ($ACTION == 0) {
        system("sh -c 'pactl -- set-sink-mute ".$LINE[0]." toggle'");
    } elsif ($ACTION == 1) {
        system("sh -c 'pactl -- set-sink-volume ".$LINE[0]." -".$DELTA."%'");
    } elsif ($ACTION == 2) {
        system("sh -c 'pactl set-sink-volume ".$LINE[0]." +".$DELTA."%'");
    } elsif ($ACTION == 3) {
        @PA_FULL = `pactl list sinks`;
        foreach(@PA_FULL) {
            if ($_ =~ /Sink #(\d+)/) {
                $sink = $1;
            }
            if ($_ =~/^\s+Volume:.* (\d+%)/) {
                $volume = $1;
                if ($LINE[0] == $sink) {
                    print $sink." ";
                    print $LINE[1]." ";
                    print $volume."\n";
                break;
                }
            }
        }
    }
}
